- name: variables from prompt
  hosts: localhost
  vars_prompt:
    - name: username
      prompt: Please enter your username
      private: false

  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: "User name is {{username}}""