- name: variables from PLAY level
  hosts: localhost
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "I am learing {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"