- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: package installation
    ansible.builtin.package:
      name: "{{item}}" # item is a default keyword
      state: present
    loop:
    - git
    - mysql
    - postfix